import React from 'react';
import './Main.modules.css';

const Main = () => {
    return (
        <div>
            <h2>Welcome to dashboard</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odio quisquam itaque ab dolorem ullam odit esse assumenda fugiat sint placeat eaque ipsum consequatur modi exercitationem necessitatibus amet dicta quo quod sit facilis, dolores nesciunt! Fuga aliquid ad, recusandae magnam, ducimus ipsa unde fugiat obcaecati tempore eos odio excepturi est sint nam dicta harum consequuntur, commodi soluta beatae! Eum molestiae quisquam eveniet assumenda atque dolor distinctio suscipit libero similique, cupiditate numquam officiis nobis praesentium quo impedit commodi quod veniam debitis, minus voluptas. Eveniet impedit reprehenderit corrupti delectus suscipit maiores cum vel error ea recusandae modi quidem incidunt, quos perspiciatis quibusdam debitis beatae saepe tenetur velit eius nemo corporis totam hic. Laboriosam saepe nostrum facilis aperiam esse consectetur deleniti, error voluptatibus necessitatibus. Quis harum blanditiis aliquam eligendi optio! A quo esse possimus animi excepturi cum, dolores nesciunt asperiores laudantium! Laudantium quam tempore molestiae. Et voluptatum accusamus alias aut! Nulla magnam accusamus, totam aspernatur dignissimos eos ullam unde blanditiis nobis quam. Earum quis unde consequuntur cupiditate nemo quam possimus, consequatur laboriosam voluptates error praesentium optio dolore. Neque, soluta, recusandae quidem perspiciatis aperiam provident corrupti eius fugit blanditiis id nulla deserunt vitae maxime molestias? Veniam mollitia quisquam deleniti laborum, tenetur officiis tempora, inventore eaque similique provident porro. Eligendi, exercitationem? Ea distinctio iure beatae quibusdam voluptatum ullam neque repudiandae tempora earum facere vitae consectetur sapiente architecto autem, sint nisi ipsam libero quae nam. Rerum, similique! Magni, nostrum omnis quo ab itaque at ipsa vitae corrupti, nisi harum molestias praesentium ad nulla temporibus iusto dolores distinctio deleniti repellat vel placeat laudantium! Distinctio, soluta sint amet nostrum saepe rerum veniam dolorem! Aliquid similique, nam beatae numquam, reprehenderit nihil sit voluptatibus eos nobis placeat et? Voluptatum cum itaque ipsa quam nulla sequi alias est vel consequuntur? Laborum ratione consequuntur cumque enim totam ad assumenda excepturi asperiores animi ullam maxime perferendis, dolore esse voluptas. Eveniet nulla quaerat at, beatae nihil voluptates deserunt vero sint totam dignissimos laboriosam. Sequi magnam voluptatem tempore unde quidem, vero quisquam blanditiis soluta neque error quibusdam accusantium eum harum, dolorum consectetur debitis minima nam est ipsam libero rerum, natus aut aperiam. Maxime temporibus molestiae corporis.</p>
        </div>
    );
};

export default Main;